version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Building the project"
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build  # Specify the output directory where the built files are located
